# Deployment управляет репликами подов и выполняет rolling-update.
# Здесь 2 реплики для базовой отказоустойчивости.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: webapp-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          # Лёгкий образ nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
